spring.application.name=ctsh_api

spring.datasource.url=jdbc:mysql://localhost:3306/ctsh_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=ctsh_user
spring.datasource.password=ctsh_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
server.servlet.context-path=/api
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.security.pepper=${CTSH_PEPPER:change-me-pepper}
app.cors.allowed-origins=http://localhost:3000
app.jwt.secret=${CTSH_JWT_SECRET:change-me-secret-change-me-secret-123456!}